#ifndef _LOSS_HPP
#define _LOSS_HPP

#include <Eigen/Dense>

namespace loss
{
    /** Basic interface for a loss function
     * 
     * @tparam T Scalar type for evaluating the loss function
     */
    template<typename T>
    class Loss
    {
        public:
        /** Evaluates the loss gradient.
         * 
         * Returns the partial gradient of the loss with respect
         * to each predicted value. The net loss is stored in the 
         * given `loss` parameter.
         * 
         * @param predicted Data generated by a model
         * @param actual Ground truth data
         * @param loss Optional reference to variable that net loss will be stored in
        */
        template<typename X>
        X grad(X&& predicted, X& actual, T& loss);
        
        template<typename X>
        X grad(X& predicted, X& actual)
        {
            T t;
            return grad(predicted, actual, t);
        }

        protected:

        /** Helper for converting Eigen vectors, matrices, and tensors to common type.
         * 
         * @param data Tensor, Vector, or Matrix to convert
         * @return Array containing flattened data 
        */
        template<typename X>
        static Eigen::Array<T, Eigen::Dynamic, 1> make_array(X& data)
        {
            return Eigen::Map<Eigen::Array<T, Eigen::Dynamic, 1>>(
                data.data(), data.size()
            );
        }
    };
}


#endif