#include "basic/Layer.hpp"
#include "basic/Sequence.hpp"
// #include "include/Autoencoder.hpp"
// #include "include/DeepAutoencoder.hpp"
// #include "include/CoupledAutoencoder.hpp"
// #include "include/Variational.hpp"
// #include "include/DenoisingAutoencoder.hpp"