#include "include/Network.hpp"
#include "include/Autoencoder.hpp"
#include "include/DeepAutoencoder.hpp"
#include "include/CoupledAutoencoder.hpp"
#include "include/Variational.hpp"
#include "include/DeepVariational.hpp"